Implement logging for albs-sign-file
AlmaLinux/albs-sign-file pull request #19
Opened 2024-11-22 09:10 UTC by Kwaizer

2024-11-25 11:41 UTC, Korulag requested changes

2024-11-25 11:41 UTC, Korulag commented on sign/pgp/pgp.py
> +                    fd.name,
Incorrect indents

2024-11-25 11:41 UTC, Korulag commented on sign/log.py
> +            ' Filename: %s. Hash before: %s. '
Remove whitespace in the beginning of the string

2024-11-25 11:41 UTC, Korulag commented on sign/utils/hashing.py
> +    return hashlib.new('sha1' if checksum_type == 'sha' else checksum_type)
Change default hasher to `sha256` since sha1 is too weak.

2024-11-29 14:18 UTC, soksanichenko requested changes

2024-11-29 14:18 UTC, soksanichenko commented on sign/pgp/pgp.py
> +        self.__syslog = SysLog(tag_name='albs-sign-service')
Make a tag name configurable, because we use that service for CLBS also

2024-12-06 09:36 UTC, anfimovdm requested changes

2024-12-06 09:36 UTC, anfimovdm commented on sign/utils/hashing.py
> +def get_hasher(checksum_type):
unused parameter

2024-12-06 09:36 UTC, anfimovdm commented on sign/utils/hashing.py
> +        hasher = get_hasher(hash_type)
same as below

2024-12-06 09:36 UTC, anfimovdm commented on sign/utils/hashing.py
> +        Hash type (e.g. sha1, sha256).
please remove it since we use only sha256 algorithm

2024-12-09 09:14 UTC, anfimovdm approved these changes

2024-12-09 12:57 UTC, Korulag approved these changes

2024-12-09 12:58 UTC, soksanichenko approved these changes

2024-12-09 13:00 UTC, merged